"""followers

Revision ID: 41936b509245
Revises: b5b028ad8091
Create Date: 2018-12-07 13:58:19.032470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41936b509245'
down_revision = 'b5b028ad8091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
