"""correct typo

Revision ID: 8c5e6fc19b50
Revises: 646b161b2ac5
Create Date: 2019-01-14 20:51:47.548301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5e6fc19b50'
down_revision = '646b161b2ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('payload_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'payload_json')
    # ### end Alembic commands ###
